/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmyshow;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author mayan
 */
public class paymentPage extends javax.swing.JFrame {

    /**
     * Creates new form paymentPage
     */
//  float GSTAmount = 0.0f , GrossAmount = 0.0f ;
    String  seat_type = "",no_seats="",food_item="",no_food="",GSTstring="",GrossString="",iconpath="";
    public paymentPage() {
        initComponents();
        setTitle("Payment Page");
        setLocationRelativeTo(null);
    }
//    private void ScaleImgFun(){
//        icon_image.setIcon(new ImageIcon(new ImageIcon(iconpath).getImage().getScaledInstance(icon_image.getWidth(),icon_image.getHeight(), Image.SCALE_AREA_AVERAGING)));
//    }
    public paymentPage(String seat_type, String no_seats, String food_item, String no_food, String GSTstring, String GrossString, String icon_path) {
        this.seat_type = seat_type;
        this.no_seats = no_seats;
 //       System.out.print(""+no_seats);
        this.food_item = food_item;
        this.no_food = no_food;
        this.GSTstring = GSTstring;
        this.GrossString = GrossString;
        this.iconpath = icon_path;
        initComponents();

        ScaleImgFun();
        setTitle("Payment Page");
        setLocationRelativeTo(null);
        infoSetup();
    }
    private void ScaleImgFun(){
        icon_image.setIcon(new ImageIcon(new ImageIcon(iconpath).getImage().getScaledInstance(icon_image.getWidth(),icon_image.getHeight(), Image.SCALE_AREA_AVERAGING)));
    }
    public String getSeat_type() {
        return seat_type;
    }

    public void setSeat_type(String seat_type) {
        this.seat_type = seat_type;
    }

    public String getNo_seats() {
        return no_seats;
    }

    public void setNo_seats(String no_seats) {
        this.no_seats = no_seats;
    }

    public String getFood_item() {
        return food_item;
    }

    public void setFood_item(String food_item) {
        this.food_item = food_item;
    }

    public String getNo_food() {
        return no_food;
    }

    public void setNo_food(String no_food) {
        this.no_food = no_food;
    }

    public String getGSTstring() {
        return GSTstring;
    }

    public void setGSTstring(String GSTstring) {
        this.GSTstring = GSTstring;
    }

    public String getGrossString() {
        return GrossString;
    }

    public void setGrossString(String GrossString) {
        this.GrossString = GrossString;
    }
    
     private void infoSetup(){
         lbl_seat_type.setText(getSeat_type());
         lbl_no_seats.setText(getNo_seats());
         lbl_food_item.setText(getFood_item());
        lbl_food_quantity.setText(getNo_food());
        lbl_gst_amount.setText( getGSTstring());
        lbl_gross_amount.setText( getGrossString());
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_seat_type = new javax.swing.JLabel();
        lbl_no_seats = new javax.swing.JLabel();
        lbl_food_item = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_gst_amount = new javax.swing.JLabel();
        lbl_gross_amount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_food_quantity = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_result = new javax.swing.JLabel();
        icon_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Seat Type :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 286, 200, 50));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENT CONFORMATION PAGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 676, 39));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("No. of Seats :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 354, 200, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Food Quantity :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 490, 200, 45));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Selected Food :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 422, 200, 50));

        lbl_seat_type.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_seat_type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_seat_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 286, 200, 50));

        lbl_no_seats.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_no_seats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_no_seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 354, 200, 50));

        lbl_food_item.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_food_item.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_food_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 422, 200, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("GST % :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 553, 200, 45));

        lbl_gst_amount.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_gst_amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_gst_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 553, 200, 50));

        lbl_gross_amount.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_gross_amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_gross_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 621, 200, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Gross Amount :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 621, 200, 45));

        lbl_food_quantity.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_food_quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_food_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 490, 200, 45));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Previous");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 745, 150, 50));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Payment");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 745, 150, 50));

        lbl_result.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_result.setForeground(new java.awt.Color(255, 102, 102));
        lbl_result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 678, 453, 49));
        jPanel1.add(icon_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 70, 150, 198));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 710, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if( no_seats.equals("") || seat_type.equals("")  || food_item.equals("") || no_food.equals("") || iconpath.equals("") ){
            lbl_result.setText("Unable to proceed Previous");
        }else{
            new BookMyShow_MainFrame(seat_type ,no_seats,food_item,no_food,GSTstring,GrossString,iconpath).show();
            this.dispose();
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        lbl_result.setText("OTP is sended");
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_food_item;
    private javax.swing.JLabel lbl_food_quantity;
    private javax.swing.JLabel lbl_gross_amount;
    private javax.swing.JLabel lbl_gst_amount;
    private javax.swing.JLabel lbl_no_seats;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_seat_type;
    // End of variables declaration//GEN-END:variables


}
